theme: jekyll-theme-hacker
title: RazviOverflow 
author: Razvi
description: Exploit code, not people. 
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
repository: RazviOverflow/razvioverflow.github.io
collections:
  microcorruption:
    output: true
  hackingwebsitelist:
    output: true
    permalink: /starthacking

defaults:
  - scope:
      path: ""
    values:
      layout: default
 
