theme: jekyll-theme-hacker
title: RazviOverflow 
description: The more you're able to hear, the more you'll learn. 
plugins:
  - jekyll-seo-tag
author:
  twitter: Razvi
repository: RazviOverflow/razvioverflow.github.io
collections:
  microcorruption:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
